######################################################################
# Automatically generated by qmake (3.0) ?? 5? 29 10:21:41 2018
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .

# Input
HEADERS += guiclass.h
SOURCES += guiclass.cpp guimain.cpp

QT+=widgets
