######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 20 14:36:31 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += guiclass.h
SOURCES += guiclass.cpp guimain.cpp
